### ISSUE TITLE
Dataset Request

### ISSUE THREAD

**Issue by yjyoo3312** [NoviceStone/HyperMiner#1]
Thank you for uploading the code,

I am trying to run the training code but couldn't find dataset pickles ('20ng', 'tmn', 'webs', 'wiki', and 'rcv').

Would you be able to share the dataset files you used? It would be a great help.

Thank you.

**Comment by yjyoo3312** [comment]
Found

**Comment by yjyoo3312** [comment]
From the SawETM Repo, I found the 20news group dataset but failed to find others. 
Where can I find the other ones? It would be appreciated if you give me the link to the datasets.

**Comment by NoviceStone** [comment]
> From the SawETM Repo, I found the 20news group dataset but failed to find others. Where can I find the other ones? It would be appreciated if you give me the link to the datasets.

Thanks for using our code. Links to our datasets are given below, and we also provide this information in the appendix.
**20ng** - http://qwone.com/~jason/20Newsgroups/
**tmn** - http://acube.di.unipi.it/tmn-dataset/
**wiki** - https://blog.salesforceairesearch.com/the-wikitext-long-term-dependency-language-modeling-dataset/
**rcv** - https://trec.nist.gov/data/reuters/reuters.html
Please cite the original paper if you use these datasets in your article.

**Comment by yjyoo3312** [comment]
> > From the SawETM Repo, I found the 20news group dataset but failed to find others. Where can I find the other ones? It would be appreciated if you give me the link to the datasets.
> 
> Thanks for using our code. Links to our datasets are given below, and we also provide this information in the appendix. **20ng** - http://qwone.com/~jason/20Newsgroups/ **tmn** - http://acube.di.unipi.it/tmn-dataset/ **wiki** - https://blog.salesforceairesearch.com/the-wikitext-long-term-dependency-language-modeling-dataset/ **rcv** - https://trec.nist.gov/data/reuters/reuters.html Please cite the original paper if you use these datasets in your article.

Thank you for noticing me! we recently published a new topic modeling paper here (https://arxiv.org/abs/2312.11532) and we cited your paper Hyperminer. we will test the datasets and share you the result. Thank you:)
